/// Validated national weekly POS observations; the intentional missing week remains blank and is not interpolated.
table National_Weekly
	lineageTag: 1c01f668-34d6-5829-b5a7-285c195ac405

	column 'Week Start'
		dataType: dateTime
		isHidden
		formatString: yyyy-MM-dd
		lineageTag: 1f258040-32bc-4fe7-9ed1-9ce35414e0fd
		summarizeBy: none
		sourceColumn: Week Start

		annotation UnderlyingDateTimeDataType = Date

	column 'Week End'
		dataType: dateTime
		isHidden
		formatString: yyyy-MM-dd
		lineageTag: a7c06c25-7082-4e6d-800b-b562bfa18dc2
		summarizeBy: none
		sourceColumn: Week End

		annotation UnderlyingDateTimeDataType = Date

	column 'Transaction Count'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 388ce257-8125-4b70-aced-a1495e5acbb1
		summarizeBy: sum
		sourceColumn: Transaction Count

	column 'Transaction Value SAR'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 192307d0-8764-4d55-b762-d577896191ba
		summarizeBy: sum
		sourceColumn: Transaction Value SAR

	column 'Average Ticket SAR'
		dataType: double
		isHidden
		formatString: 0.00
		lineageTag: a64ad813-9a48-437b-ab27-3aa026cb81fa
		summarizeBy: sum
		sourceColumn: Average Ticket SAR

		annotation SummarizationSetBy = Automatic

	column 'Data Status'
		dataType: string
		isHidden
		lineageTag: 168649aa-2aea-4da4-b7d4-f221a4a202d8
		summarizeBy: none
		sourceColumn: Data Status

	partition National_Weekly = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataRoot & "\National_Weekly.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(PromotedHeaders, {{"Week Start", type date}, {"Week End", type date}, {"Transaction Count", Int64.Type}, {"Transaction Value SAR", Int64.Type}, {"Average Ticket SAR", type number}, {"Data Status", type text}}, "en-US")
				in
				    Typed

